[package]
name = "client"
version = "0.1.0"
authors = ["Anthony Dodd <dodd.anthonyjosiah@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
bytes = "0.4"
futures = "0.1"
js-sys = "=0.3.17"
log = "0.4"
prost = "0.5"
seed = "0.3"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
wasm-bindgen = "=0.2.40"
web-sys = { version="=0.3.17", features=["WebSocket", "MessageEvent", "BinaryType"] }

[build-dependencies]
prost-build = "0.5"
