version: '3'
services:
  server:
    build: .
    ports:
      - 8080:8080
    env_file: ./env/dev

  mongo:
    image: mongo:4.0
    ports:
      - 27017
    volumes:
      - mongo:/data/db

volumes:
  mongo:
