version: '3'
services:
  server-watcher:
    build: .
    command: cargo make watch-server-run
    ports:
      - 8081:8080
    volumes:
      - ./common:/api/common
      - ./server:/api/server
      - ./static:/api/static
      - ./Cargo.toml:/api/Cargo.toml
      - ./Cargo.lock:/api/Cargo.lock
      - ./Makefile.toml:/api/Makefile.toml
    env_file: ./env/dev

  client-watcher:
    build: .
    command: cargo make watch-client
    volumes:
      - ./client:/api/client
      - ./common:/api/common
      - ./static:/api/static
      - ./Cargo.toml:/api/Cargo.toml
      - ./Cargo.lock:/api/Cargo.lock
      - ./Makefile.toml:/api/Makefile.toml

  mongo_dev:
    image: mongo:4.0
    container_name: mongo
    ports:
      - 27017
    volumes:
      - mongo_dev:/data/db

volumes:
  mongo_dev:
