# TODO:
# - add notes on: `cargo make --no-workspace ...` to make this work intuitively.
# - ensure wasm32-unknown-unknown is installed.

[tasks.client-build]
workspace = false
command = "cargo"
args = ["build", "-p", "client", "--release", "--target", "wasm32-unknown-unknown"]

[tasks.client-bindgen]
workspace = false
install_crate = { crate_name="wasm-bindgen-cli", binary="wasm-bindgen", test_arg="--help" }
command = "wasm-bindgen"
args = ["target/wasm32-unknown-unknown/release/client.wasm", "--no-modules", "--out-dir", "./static"]

[tasks.client-static]
workspace = false
script_runner = "@shell"
script = ['''
cp ./client/index.html ./static
''']

[tasks.server-build]
workspace = false
command = "cargo"
args = ["build", "-p", "server", "--release"]

[tasks.app-build]
workspace = false
dependencies = [
    "client-build",
    "client-bindgen",
    "client-static",
    "server-build",
]

[tasks.client-flow]
workspace = false
dependencies = ["client-build", "client-bindgen", "client-static"]

[tasks.watch-client]
workspace = false
command = "cargo"
args = ["watch", "-w", "client", "-i", "client/src/proto/*", "-s", "cargo make client-flow"]

[tasks.watch-server-run]
workspace = false
command = "cargo"
args = ["watch", "-w", "server", "-i", "server/src/proto/*", "-s", "cargo run -p server --release"]
